---
remove_experimental_mysql: false

mysql_debian_pkgs_default:
  - python3-mysqldb
mysql_release_specific_debian_pkgs:
  xenial:
    - python-mysqldb
  bionic:
    - python-mysqldb
  focal:
    - python3-mysqldb
mysql_debian_pkgs: "{{ mysql_debian_pkgs_default + mysql_release_specific_debian_pkgs[ansible_distribution_release] }}"

mysql_server_pkg: "{{ 'mysql-server-8.0' if mysql_server_version_8_0 is defined and (mysql_server_version_8_0 | bool) else 'mysql-server-8.0' }}"
mysql_server_8_0_pkg: "mysql-server=8.0.*"
mysql_client_8_0_pkg: "mysql-client=8.0.*"
mysql_community_server_8_0_pkg: "mysql-server=8.0.*"

mysql_dir: /etc/mysql

mysql_socket: /var/run/mysqld/mysqld.sock

mysql_8_0_install: true

mysql_server_8_0_pkgs:
   - mysql-client-8.0
   - mysql-client-core-8.0
   - mysql-common
   - mysql-server-8.0
   - mysql-server-core-8.0

DEFAULT_MYSQL_CHARACTER_SET: utf8
DEFAULT_MYSQL_COLLATION: utf8_general_ci

MYSQL_APT_KEYSERVER: "keyserver.ubuntu.com"
MYSQL_APT_KEY: "467B942D3A79BD29"
MYSQL_REPO: "deb http://repo.mysql.com/apt//ubuntu/ focal mysql-8.0"
