---
- name: Look for mysql 8.0
  shell: "dpkg -s mysql-server"
  ignore_errors: yes
  register: mysql_80_installed
  changed_when: no

- name: Important message
  debug:
    msg: |
      "MySQL experimental is already installed, make 'remove_experimental_mysql: true' in defaults/main.yml, 
      if you want to remove it and install the stable version of MySQL"
  when: "'8.0.27' in  mysql_56_installed.stdout and not remove_experimental_mysql"

- pause:
    seconds: 10
  when: "'8.0.27' in  mysql_56_installed.stdout and not remove_experimental_mysql"

# remove this, once the new devstack is out
- include: remove_mysql_experimental.yml
  when: remove_experimental_mysql

- include: mysql.yml
  when: (mysql_80_installed.rc == 1) or (remove_experimental_mysql)
